-- Travel Story business data schema
-- Run this once in the Production Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint primary key,
  name text not null unique,
  image text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null check (price >= 0),
  expense numeric(12,2) not null default 0 check (expense >= 0),
  stock integer not null default 0 check (stock >= 0),
  image text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint primary key,
  name text not null,
  mobile text not null,
  place text not null default '',
  balance numeric(12,2) not null default 0 check (balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bills (
  id bigint primary key,
  bill_no text not null unique,
  bill_date date not null,
  customer_id bigint references public.customers(id) on delete set null,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  total numeric(12,2) not null check (total >= 0),
  paid numeric(12,2) not null default 0 check (paid >= 0),
  balance numeric(12,2) not null default 0 check (balance >= 0),
  payment text not null check (payment in ('Cash','GPay / UPI','Credit')),
  expense numeric(12,2) not null default 0 check (expense >= 0),
  profit numeric(12,2) not null default 0,
  status text not null default 'Completed' check (status = 'Completed'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bill_items (
  id bigint generated by default as identity primary key,
  bill_id bigint not null references public.bills(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  name_snapshot text not null,
  qty integer not null check (qty > 0),
  price numeric(12,2) not null check (price >= 0),
  expense numeric(12,2) not null default 0 check (expense >= 0),
  total numeric(12,2) not null check (total >= 0)
);

create table if not exists public.stock_logs (
  id bigint primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  product_name_snapshot text not null,
  qty integer not null check (qty > 0),
  expense numeric(12,2) not null default 0 check (expense >= 0),
  log_date date not null,
  type text not null check (type in ('Purchase','Adjustment')),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint primary key,
  expense_date date not null,
  category text not null,
  description text not null default '',
  amount numeric(12,2) not null check (amount >= 0),
  added_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint primary key,
  inquiry_date date not null,
  customer_name text not null,
  mobile text not null,
  place text not null default '',
  product text not null default '',
  description text not null default '',
  status text not null default 'New' check (status in ('New','Contacted','Closed')),
  added_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_users (
  id bigint primary key,
  username text not null unique,
  name text not null,
  role text not null check (role in ('admin','staff')),
  password_hash text not null,
  permissions jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_customers_mobile on public.customers(mobile);
create index if not exists idx_bills_date on public.bills(bill_date desc);
create index if not exists idx_bills_customer on public.bills(customer_id);
create index if not exists idx_bill_items_bill on public.bill_items(bill_id);
create index if not exists idx_stock_logs_product on public.stock_logs(product_id);
create index if not exists idx_stock_logs_date on public.stock_logs(log_date desc);
create index if not exists idx_expenses_date on public.expenses(expense_date desc);
create index if not exists idx_inquiries_date on public.inquiries(inquiry_date desc);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.bills enable row level security;
alter table public.bill_items enable row level security;
alter table public.stock_logs enable row level security;
alter table public.expenses enable row level security;
alter table public.inquiries enable row level security;
alter table public.staff_users enable row level security;

-- Application access is through protected Next.js server routes using the
-- service-role key. No anonymous browser policies are created here.
