'use client';
import {useState} from 'react';
import {Save,ShieldCheck,Trash2,LockKeyhole,UserPlus,KeyRound,UserCog} from 'lucide-react';
import {useStore,PERMISSIONS,Permission,User} from '@/lib/store';
import {Panel} from '@/components/Panel';
const permissionLabels:Record<Permission,string>={dashboard:'Dashboard',products:'Products',sales:'Sales / Billing',stock:'Stock Management',reports:'Reports',bills:'Bills & History',customers:'Customers',settings:'Settings'};
const safePermissions=(u:User)=>u.permissions||[];
export default function Settings(){
 const{role,currentUser,users,setUsers,products,customers,bills,setProducts,setCustomers,setBills,setStockLogs,toast}=useStore();
 const[oldPass,setOldPass]=useState('');const[newPass,setNewPass]=useState('');const[confirmPass,setConfirmPass]=useState('');
 const[name,setName]=useState('');const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[permissions,setPermissions]=useState<Permission[]>(['sales','customers']);
 function changePassword(){if(!currentUser||oldPass!==currentUser.password){toast('Current password is incorrect');return}if(newPass.length<6){toast('New password must be at least 6 characters');return}if(newPass!==confirmPass){toast('Passwords do not match');return}setUsers(v=>v.map(u=>u.id===currentUser.id?{...u,password:newPass,permissions:safePermissions(u)}:u));setOldPass('');setNewPass('');setConfirmPass('');toast('Password changed successfully')}
 function createStaff(){const u=username.trim();const n=name.trim();if(!u||!n||password.length<6){toast('Enter name, username and a password of 6+ characters');return}if(users.some(x=>x.username.toLowerCase()===u.toLowerCase())){toast('Username already exists');return}if(!permissions.length){toast('Select at least one access permission');return}const user:User={id:Date.now(),username:u,password,role:'staff',name:n,permissions};setUsers(v=>[...v,user]);setName('');setUsername('');setPassword('');setPermissions(['sales','customers']);toast('Staff account created')}
 function togglePermission(p:Permission){setPermissions(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p])}
 function reset(){if(confirm('Reset all Travel Story demo data?')){localStorage.removeItem('noor_products_v4');localStorage.removeItem('noor_customers_v4');localStorage.removeItem('noor_bills_v4');localStorage.removeItem('noor_stock_logs_v4');setProducts([]);setCustomers([]);setBills([]);setStockLogs([]);toast('Demo data reset')}}
 return <div className="settings-grid">
  <Panel><h3>Store Settings</h3><label>Store Name<input defaultValue="Travel Story"/></label><label>WhatsApp Number<input defaultValue="919999999999"/></label><label>Currency<input defaultValue="INR (₹)"/></label><button className="primary-btn"><Save/>Save Settings</button></Panel>
  <Panel><h3><ShieldCheck/> Account & Access</h3><div className="access"><b>Logged in as</b><span>{currentUser?.name||'Administrator'}</span></div><div className="privacy"><LockKeyhole/><span>Expense and profit values are visible only to Admin.</span></div>{role==='admin'&&<button className="danger-wide" onClick={reset}><Trash2/>Reset Demo Data</button>}</Panel>
  {currentUser&&<Panel><h3><KeyRound/> Change Password</h3><label>Current Password<input type="password" value={oldPass} onChange={e=>setOldPass(e.target.value)} /></label><label>New Password<input type="password" value={newPass} onChange={e=>setNewPass(e.target.value)} /></label><label>Confirm New Password<input type="password" value={confirmPass} onChange={e=>setConfirmPass(e.target.value)} /></label><button className="primary-btn" onClick={changePassword}><KeyRound/>Change Password</button></Panel>}
  {role==='admin'&&<Panel className="staff-management"><h3><UserPlus/> Create Staff Login</h3><div className="form-grid"><label>Staff Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Accounts Staff"/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Login username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters"/></label></div><b className="access-title">Page Access</b><div className="permission-grid">{PERMISSIONS.map(p=><label className="check-item" key={p}><input type="checkbox" checked={permissions.includes(p)} onChange={()=>togglePermission(p)}/><span>{permissionLabels[p]}</span></label>)}</div><button className="primary-btn" onClick={createStaff}><UserCog/>Create Staff Account</button><div className="staff-list">{users.filter(u=>u.role==='staff').map(u=><div className="staff-row" key={u.id}><div><b>{u.name}</b><small>@{u.username} · {safePermissions(u).length} pages</small></div><span>Staff</span></div>)}</div></Panel>}
  <Panel><h3>Data Overview</h3><div className="overview"><span>Products <b>{products.length}</b></span><span>Customers <b>{customers.length}</b></span><span>Bills <b>{bills.length}</b></span></div></Panel>
 </div>
}
