'use client';
import {useEffect,useState} from 'react';
import {KeyRound,UserPlus,Store,Palette,Image as ImageIcon,X,Save,Upload,ChevronRight,ShieldCheck} from 'lucide-react';
import {useStore,PERMISSIONS,Permission,User} from '@/lib/store';
import {DEFAULT_SITE_SETTINGS,saveSiteSettings,useSiteSettings,SiteSettings} from '@/lib/site-settings';

type Modal='store'|'theme'|'logo'|'password'|'staff'|null;
const labels:Record<Permission,string>={dashboard:'Dashboard',products:'Products',sales:'Sales / Billing',stock:'Stock Management',reports:'Reports',bills:'Bills & History',customers:'Customers',settings:'Settings'};
const safe=(u:User)=>u.permissions||[];

export default function Settings(){
 const{role,currentUser,users,setUsers,toast}=useStore();const site=useSiteSettings();const[modal,setModal]=useState<Modal>(null);const[form,setForm]=useState<SiteSettings>(site);
 const[oldPass,setOldPass]=useState('');const[newPass,setNewPass]=useState('');const[confirmPass,setConfirmPass]=useState('');const[name,setName]=useState('');const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[permissions,setPermissions]=useState<Permission[]>(['sales','customers']);
 useEffect(()=>setForm(site),[site.storeName,site.whatsapp,site.currency,site.theme,site.accent,site.headerTitle,site.logo]);
 const close=()=>setModal(null);
 function save(partial?:Partial<SiteSettings>){const next={...form,...partial};setForm(next);saveSiteSettings(next);close();toast('Settings saved and published')}
 function changePassword(){if(!currentUser||oldPass!==currentUser.password){toast('Current password is incorrect');return}if(newPass.length<6){toast('New password must be at least 6 characters');return}if(newPass!==confirmPass){toast('Passwords do not match');return}setUsers(v=>v.map(u=>u.id===currentUser.id?{...u,password:newPass,permissions:safe(u)}:u));setOldPass('');setNewPass('');setConfirmPass('');close();toast('Password changed successfully')}
 function createStaff(){const u=username.trim(),n=name.trim();if(!u||!n||password.length<6){toast('Enter name, username and a password of 6+ characters');return}if(users.some(x=>x.username.toLowerCase()===u.toLowerCase())){toast('Username already exists');return}if(!permissions.length){toast('Select at least one access permission');return}setUsers(v=>[...v,{id:Date.now(),username:u,password,role:'staff',name:n,permissions}]);setName('');setUsername('');setPassword('');setPermissions(['sales','customers']);close();toast('Staff account created')}
 return <div className="settings-v2">
  <div className="settings-v2-head"><div><span>TRAVEL STORY</span><h2>Settings</h2><p>Store controls, appearance, branding and access — all saved to this browser.</p></div><div className="settings-status"><ShieldCheck size={16}/> {role==='admin'?'Administrator':'Staff Account'}</div></div>
  <div className="settings-v2-grid"><Card icon={<Store/>} tag="GENERAL" title="Store Settings" desc="Store name, WhatsApp number and currency." onClick={()=>setModal('store')}/><Card icon={<Palette/>} tag="DESIGN" title="Theme & Appearance" desc="Choose a theme and accent that fits your Travel Story logo." onClick={()=>setModal('theme')}/><Card icon={<ImageIcon/>} tag="BRANDING" title="Logo & Branding" desc="Change the logo and heading shown throughout the site." onClick={()=>setModal('logo')}/><Card icon={<KeyRound/>} tag="SECURITY" title="Change Password" desc="Update the password for the current account." onClick={()=>setModal('password')}/>{role==='admin'&&<Card icon={<UserPlus/>} tag="ADMIN ONLY" title="Staff Management" desc="Create staff logins and choose exactly which pages they can access." onClick={()=>setModal('staff')}/>}</div>
  {modal&&<div className="settings-v2-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="settings-v2-modal"><button className="settings-v2-x" onClick={close}><X size={18}/></button>
   {modal==='store'&&<><Head icon={<Store/>} title="Store Settings" text="These values are used by the homepage, receipts and WhatsApp actions."/><Field label="Store Name" value={form.storeName} onChange={v=>setForm({...form,storeName:v})}/><Field label="WhatsApp Number" value={form.whatsapp} onChange={v=>setForm({...form,whatsapp:v})} placeholder="919876543210"/><Field label="Currency" value={form.currency} onChange={v=>setForm({...form,currency:v})}/><Actions cancel={close} save={()=>save()} /></>}
   {modal==='theme'&&<><Head icon={<Palette/>} title="Theme & Appearance" text="Save once and the selected colors are applied across the homepage and admin area."/><div className="theme-grid-v2">{[['Emerald Luxury','Green · Cream · Gold','linear-gradient(135deg,#075642,#d7bd82)'],['Midnight Gold','Deep · Gold · Cream','linear-gradient(135deg,#10251f,#c69b52)'],['Travel Teal','Teal · Sand · Gold','linear-gradient(135deg,#0d5960,#e5c795)'],['Royal Plum','Plum · Champagne · Cream','linear-gradient(135deg,#4d315c,#d8c29a)'],['Ocean Sand','Ocean · Ivory · Bronze','linear-gradient(135deg,#23556a,#dfc59a)']].map(([name,text,bg])=><button key={name} className={form.theme===name?'chosen':''} onClick={()=>setForm({...form,theme:name})}><i style={{background:bg}}/><b>{name}</b><small>{text}</small></button>)}</div><label className="v2-label">Accent Style<select value={form.accent} onChange={e=>setForm({...form,accent:e.target.value})}><option>Forest Green</option><option>Warm Gold</option><option>Deep Teal</option><option>Plum</option><option>Ocean Blue</option></select></label><Actions cancel={close} save={()=>save()} /></>}
   {modal==='logo'&&<><Head icon={<ImageIcon/>} title="Logo & Branding" text="Changes here are reflected in the sidebar, admin header, homepage and login popup."/><div className="logo-preview-v2"><img src={form.logo||DEFAULT_SITE_SETTINGS.logo}/><div><b>{form.headerTitle}</b><small>Live branding preview</small></div></div><Field label="Brand Heading" value={form.headerTitle} onChange={v=>setForm({...form,headerTitle:v})}/><Field label="Logo Image URL" value={form.logo} onChange={v=>setForm({...form,logo:v})}/><label className="upload-v2"><Upload size={17}/> Upload new logo<input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){toast('Logo must be 2MB or smaller');return}const reader=new FileReader();reader.onload=()=>setForm(v=>({...v,logo:String(reader.result||'')}));reader.readAsDataURL(file)}}/></label><Actions cancel={close} save={()=>save()} /></>}
   {modal==='password'&&<><Head icon={<KeyRound/>} title="Change Password" text="Change the password used by this account to log in."/><Field label="Current Password" type="password" value={oldPass} onChange={setOldPass}/><Field label="New Password" type="password" value={newPass} onChange={setNewPass} placeholder="Minimum 6 characters"/><Field label="Confirm New Password" type="password" value={confirmPass} onChange={setConfirmPass}/><Actions cancel={close} save={changePassword} /></>}
   {modal==='staff'&&role==='admin'&&<><Head icon={<UserPlus/>} title="Staff Management" text="Create another login and control the pages that account staff can see."/><Field label="Staff Name" value={name} onChange={setName} placeholder="e.g. Accounts Staff"/><div className="v2-two"><Field label="Username" value={username} onChange={setUsername}/><Field label="Password" type="password" value={password} onChange={setPassword}/></div><div className="access-title">PAGE ACCESS</div><div className="access-grid">{PERMISSIONS.map(p=><label key={p}><input type="checkbox" checked={permissions.includes(p)} onChange={()=>setPermissions(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p])}/>{labels[p]}</label>)}</div><button className="v2-primary full" onClick={createStaff}><UserPlus size={16}/>Create Staff Account</button><div className="existing-title">EXISTING STAFF</div>{users.filter(u=>u.role==='staff').map(u=><div className="staff-row-v2" key={u.id}><span>{u.name.slice(0,1).toUpperCase()}</span><div><b>{u.name}</b><small>@{u.username} · {safe(u).length} pages</small></div></div>)}</>}
  </div></div>}
 </div>
}
function Card({icon,tag,title,desc,onClick}:{icon:React.ReactNode;tag:string;title:string;desc:string;onClick:()=>void}){return <button className="settings-v2-card" onClick={onClick}><div className="v2-card-top"><span className="v2-icon">{icon}</span><em>{tag}</em></div><h3>{title}</h3><p>{desc}</p><b className="v2-open">Open <ChevronRight size={15}/></b></button>}
function Head({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="v2-modal-head"><span>{icon}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
function Field({label,value,onChange,type='text',placeholder}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="v2-label">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Actions({cancel,save}:{cancel:()=>void;save:()=>void}){return <div className="v2-actions"><button className="v2-cancel" onClick={cancel}>Cancel</button><button className="v2-primary" onClick={save}><Save size={16}/>Save</button></div>}
