'use client';
import {useState} from 'react';
import {Save,KeyRound,UserPlus,UserCog,Store,Palette,Image,ChevronRight,X,Upload,Eye} from 'lucide-react';
import {useStore,PERMISSIONS,Permission,User} from '@/lib/store';

type ModalType='store'|'theme'|'logo'|'password'|'staff'|null;
const permissionLabels:Record<Permission,string>={dashboard:'Dashboard',products:'Products',sales:'Sales / Billing',stock:'Stock Management',reports:'Reports',bills:'Bills & History',customers:'Customers',settings:'Settings'};
const safePermissions=(u:User)=>u.permissions||[];

export default function Settings(){
 const{role,currentUser,users,setUsers,toast}=useStore();
 const[modal,setModal]=useState<ModalType>(null);
 const[oldPass,setOldPass]=useState('');const[newPass,setNewPass]=useState('');const[confirmPass,setConfirmPass]=useState('');
 const[name,setName]=useState('');const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[permissions,setPermissions]=useState<Permission[]>(['sales','customers']);
 const[storeName,setStoreName]=useState('Travel Story');const[whatsapp,setWhatsapp]=useState('919999999999');const[currency,setCurrency]=useState('INR (₹)');
 const[theme,setTheme]=useState('Emerald Luxury');const[accent,setAccent]=useState('Forest Green');const[headerTitle,setHeaderTitle]=useState('Travel Story');
 const[logoPreview,setLogoPreview]=useState('/travel-story-logo.jpeg');
 function close(){setModal(null)}
 function changePassword(){if(!currentUser||oldPass!==currentUser.password){toast('Current password is incorrect');return}if(newPass.length<6){toast('New password must be at least 6 characters');return}if(newPass!==confirmPass){toast('Passwords do not match');return}setUsers(v=>v.map(u=>u.id===currentUser.id?{...u,password:newPass,permissions:safePermissions(u)}:u));setOldPass('');setNewPass('');setConfirmPass('');close();toast('Password changed successfully')}
 function createStaff(){const u=username.trim(),n=name.trim();if(!u||!n||password.length<6){toast('Enter name, username and a password of 6+ characters');return}if(users.some(x=>x.username.toLowerCase()===u.toLowerCase())){toast('Username already exists');return}if(!permissions.length){toast('Select at least one access permission');return}setUsers(v=>[...v,{id:Date.now(),username:u,password,role:'staff',name:n,permissions}]);setName('');setUsername('');setPassword('');setPermissions(['sales','customers']);close();toast('Staff account created')}
 function saveStore(){localStorage.setItem('travel_store_name',storeName);localStorage.setItem('travel_whatsapp',whatsapp);localStorage.setItem('travel_currency',currency);localStorage.setItem('travel_header_title',headerTitle);close();toast('Store settings saved')}
 function saveTheme(){localStorage.setItem('travel_theme',theme);localStorage.setItem('travel_accent',accent);close();toast('Theme preferences saved')}
 function saveLogo(){localStorage.setItem('travel_logo',logoPreview);localStorage.setItem('travel_header_title',headerTitle);close();toast('Branding saved')}
 return <div className="settings-page">
  <div className="settings-intro"><div><div className="settings-kicker">TRAVEL STORY</div><h2>Settings</h2><p>Customize your store, appearance and staff access.</p></div><div className="settings-badge"><Eye size={16}/><span>{role==='admin'?'Administrator':'Staff Account'}</span></div></div>
  <div className="settings-cards">
   <SettingCard icon={<Store/>} title="Store Settings" desc="Store name, WhatsApp number & currency" tag="GENERAL" onClick={()=>setModal('store')}/>
   <SettingCard icon={<Palette/>} title="Theme & Appearance" desc="Choose homepage theme and accent style" tag="DESIGN" onClick={()=>setModal('theme')}/>
   <SettingCard icon={<Image/>} title="Logo & Branding" desc="Change logo and Travel Story heading" tag="BRANDING" onClick={()=>setModal('logo')}/>
   <SettingCard icon={<KeyRound/>} title="Change Password" desc="Update the current account password" tag="SECURITY" onClick={()=>setModal('password')}/>
   {role==='admin'&&<SettingCard icon={<UserPlus/>} title="Staff Management" desc="Create staff accounts and choose page access" tag="ADMIN ONLY" onClick={()=>setModal('staff')}/>} 
  </div>
  {modal&&<div className="settings-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="settings-modal"><button className="settings-close" onClick={close}><X size={18}/></button>
   {modal==='store'&&<><ModalHeader icon={<Store/>} title="Store Settings" subtitle="Basic store information used across the site."/><div className="modal-form"><label>Store Name<input value={storeName} onChange={e=>setStoreName(e.target.value)}/></label><label>WhatsApp Number<input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/></label><label>Currency<input value={currency} onChange={e=>setCurrency(e.target.value)}/></label></div><ModalActions onCancel={close} onSave={saveStore} text="Save Settings" icon={<Save size={16}/>}/></>}
   {modal==='theme'&&<><ModalHeader icon={<Palette/>} title="Theme & Appearance" subtitle="Set the visual style for your Travel Story storefront."/><div className="theme-options"><button className={theme==='Emerald Luxury'?'selected':''} onClick={()=>setTheme('Emerald Luxury')}><span className="theme-swatch emerald"></span><b>Emerald Luxury</b><small>Green · Cream · Gold</small></button><button className={theme==='Midnight Gold'?'selected':''} onClick={()=>setTheme('Midnight Gold')}><span className="theme-swatch midnight"></span><b>Midnight Gold</b><small>Dark · Gold · Cream</small></button><button className={theme==='Soft Sand'?'selected':''} onClick={()=>setTheme('Soft Sand')}><span className="theme-swatch sand"></span><b>Soft Sand</b><small>Beige · Forest · Gold</small></button></div><label>Accent Style<select value={accent} onChange={e=>setAccent(e.target.value)}><option>Forest Green</option><option>Warm Gold</option><option>Deep Teal</option></select></label><ModalActions onCancel={close} onSave={saveTheme} text="Save Appearance" icon={<Palette size={16}/>}/></>}
   {modal==='logo'&&<><ModalHeader icon={<Image/>} title="Logo & Branding" subtitle="Control the logo and the heading displayed above the admin pages."/><div className="brand-preview"><img src={logoPreview} alt="Travel Story logo"/><div><b>{headerTitle}</b><span>Admin header title</span></div></div><label>Travel Story Heading<input value={headerTitle} onChange={e=>setHeaderTitle(e.target.value)} placeholder="Travel Story"/></label><label>Logo Image URL<input value={logoPreview} onChange={e=>setLogoPreview(e.target.value)} placeholder="/travel-story-logo.jpeg or https://..."/></label><label className="upload-label"><span><Upload size={16}/> Upload new logo (browser preview)</span><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setLogoPreview(String(r.result));r.readAsDataURL(f)}}/></label><ModalActions onCancel={close} onSave={saveLogo} text="Save Branding" icon={<Image size={16}/>}/></>}
   {modal==='password'&&<><ModalHeader icon={<KeyRound/>} title="Change Password" subtitle="Update your current login password."/><div className="modal-form"><label>Current Password<input type="password" value={oldPass} onChange={e=>setOldPass(e.target.value)} placeholder="Enter current password"/></label><label>New Password<input type="password" value={newPass} onChange={e=>setNewPass(e.target.value)} placeholder="Minimum 6 characters"/></label><label>Confirm New Password<input type="password" value={confirmPass} onChange={e=>setConfirmPass(e.target.value)} placeholder="Re-enter new password"/></label></div><ModalActions onCancel={close} onSave={changePassword} text="Change Password" icon={<KeyRound size={16}/>}/></>}
   {modal==='staff'&&role==='admin'&&<><ModalHeader icon={<UserPlus/>} title="Staff Management" subtitle="Create a staff login and choose exactly which pages they can access."/><div className="modal-form"><label>Staff Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Accounts Staff"/></label><div className="two-inputs"><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Login username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters"/></label></div><div className="section-label">PAGE ACCESS</div><div className="permission-grid">{PERMISSIONS.map(p=><label className="permission-item" key={p}><input type="checkbox" checked={permissions.includes(p)} onChange={()=>setPermissions(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p])}/><span>{permissionLabels[p]}</span></label>)}</div></div><button className="primary-btn modal-main-btn" onClick={createStaff}><UserCog size={17}/>Create Staff Account</button><div className="staff-existing"><div className="section-label">EXISTING STAFF</div>{users.filter(u=>u.role==='staff').map(u=><div className="existing-staff" key={u.id}><div className="mini-avatar">{u.name.slice(0,1).toUpperCase()}</div><div><b>{u.name}</b><span>@{u.username} · {safePermissions(u).length} pages</span></div><em>STAFF</em></div>)}</div></>}
  </div></div>}
 </div>
}
function SettingCard({icon,title,desc,tag,onClick}:{icon:React.ReactNode;title:string;desc:string;tag:string;onClick:()=>void}){return <button className="settings-card" onClick={onClick}><div className="settings-card-top"><span className="settings-icon">{icon}</span><span className="settings-tag">{tag}</span></div><div className="settings-card-title">{title}</div><div className="settings-card-desc">{desc}</div><div className="settings-open">Open <ChevronRight size={15}/></div></button>}
function ModalHeader({icon,title,subtitle}:{icon:React.ReactNode;title:string;subtitle:string}){return <div className="modal-head"><span className="modal-head-icon">{icon}</span><div><h3>{title}</h3><p>{subtitle}</p></div></div>}
function ModalActions({onCancel,onSave,text,icon}:{onCancel:()=>void;onSave:()=>void;text:string;icon:React.ReactNode}){return <div className="modal-actions"><button className="ghost-btn" onClick={onCancel}>Cancel</button><button className="primary-btn" onClick={onSave}>{icon}{text}</button></div>}
