import {NextResponse} from 'next/server';
import {createHmac,randomBytes,pbkdf2Sync,timingSafeEqual} from 'crypto';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
const endpoint=url?`${url.replace(/\/$/,'')}/rest/v1`:'';
const COOKIE='travelstore_session';
const PERMISSIONS=['dashboard','products','sales','stock','expenses','reports','bills','customers','inquiry','settings','categories'] as const;
type Permission=typeof PERMISSIONS[number];
type Role='admin'|'staff';
type Session={userId:number;username:string;name:string;role:Role;permissions:Permission[];exp:number};
function headers(extra:Record<string,string>={}){return {'apikey':key||'','Authorization':`Bearer ${key||''}`,'Content-Type':'application/json','Accept':'application/json',...extra}}
function api(resource:string){return endpoint?`${endpoint}/${resource}`:''}
function config(){return !!endpoint&&!!key}
function sign(payload:Session){const body=Buffer.from(JSON.stringify(payload)).toString('base64url');const secret=process.env.TRAVEL_SESSION_SECRET||key||'';return `${body}.${createHmac('sha256',secret).update(body).digest('base64url')}`}
function readSession(request:Request):Session|null{const raw=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${COOKIE}=`))?.slice(COOKIE.length+1);if(!raw)return null;try{const [body,sig]=raw.split('.');const secret=process.env.TRAVEL_SESSION_SECRET||key||'';const expected=createHmac('sha256',secret).update(body).digest('base64url');if(!sig||sig!==expected)return null;const s=JSON.parse(Buffer.from(body,'base64url').toString()) as Session;if(!s.exp||s.exp<Date.now())return null;return s}catch{return null}}
function hashPassword(password:string,salt=randomBytes(16).toString('hex')){return `pbkdf2:${salt}:${pbkdf2Sync(password,salt,120000,32,'sha256').toString('hex')}`}
function verifyPassword(password:string,stored:string){const [kind,salt,hash]=stored.split(':');if(kind!=='pbkdf2'||!salt||!hash)return false;const actual=pbkdf2Sync(password,salt,120000,32,'sha256').toString('hex');return actual.length===hash.length&&timingSafeEqual(Buffer.from(actual),Buffer.from(hash))}
async function db(path:string,init:RequestInit={}){return fetch(api(path),{...init,headers:{...headers(),...(init.headers||{})},cache:'no-store'})}
async function ensureDemoUsers(){const r=await db('staff_users?select=id&limit=1');if(!r.ok)throw new Error('staff_users table is not available');const rows=await r.json();if(rows.length)return;const permissions=[...PERMISSIONS];const staff=permissions.filter(x=>x!=='categories');await db('staff_users',{method:'POST',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify([{id:1,username:'admin',name:'Administrator',role:'admin',password_hash:hashPassword('admin123'),permissions,active:true},{id:2,username:'staff',name:'Staff Member',role:'staff',password_hash:hashPassword('staff123'),permissions:staff,active:true}])})}
function safeUser(x:any){return{id:Number(x.id),username:String(x.username),name:String(x.name),role:x.role as Role,permissions:(Array.isArray(x.permissions)?x.permissions:[]) as Permission[]}}
async function authLogin(request:Request){if(!config())return NextResponse.json({error:'Supabase is not configured'},{status:503});const body=await request.json().catch(()=>null);const username=String(body?.username||'').trim();const password=String(body?.password||'');if(!username||!password)return NextResponse.json({error:'Username and password are required'},{status:400});await ensureDemoUsers();const r=await db(`staff_users?select=id,username,name,role,password_hash,permissions,active&username=eq.${encodeURIComponent(username)}&limit=1`);if(!r.ok)return NextResponse.json({error:'Unable to read users'},{status:r.status});const rows=await r.json();const found=rows[0];if(!found||!found.active||!verifyPassword(password,found.password_hash))return NextResponse.json({error:'Invalid username or password'},{status:401});const u=safeUser(found);const session:Session={userId:u.id,username:u.username,name:u.name,role:u.role,permissions:u.permissions,exp:Date.now()+7*24*60*60*1000};const response=NextResponse.json({user:u});response.cookies.set(COOKIE,sign(session),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:7*24*60*60});return response}
async function session(request:Request){const s=readSession(request);return s?NextResponse.json({user:{id:s.userId,username:s.username,name:s.name,role:s.role,permissions:s.permissions}}):NextResponse.json({user:null},{status:401})}
async function logout(){const response=NextResponse.json({ok:true});response.cookies.set(COOKIE,'',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:0});return response}
async function settingsGet(){if(!config())return NextResponse.json({error:'Cloud settings are not configured'},{status:503});const res=await db('site_settings?select=settings&id=eq.1');if(!res.ok)return NextResponse.json({error:'Unable to read cloud settings'},{status:res.status});const rows=await res.json();if(!rows?.length)return NextResponse.json({settings:null},{status:404});return NextResponse.json({settings:rows[0].settings})}
async function settingsPut(request:Request){if(!config())return NextResponse.json({error:'Cloud settings are not configured'},{status:503});const body=await request.json();const res=await db('site_settings?on_conflict=id',{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id:1,settings:body})});if(!res.ok)return NextResponse.json({error:'Unable to save cloud settings'},{status:res.status});const rows=await res.json();return NextResponse.json({settings:rows?.[0]?.settings||body})}
async function catalog(){if(!config())return NextResponse.json({error:'Cloud database is not configured'},{status:503});const [p,c]=await Promise.all([db('products?select=id,name,category,price,expense,stock,image,active&order=name.asc'),db('categories?select=id,name,image&order=id.asc')]);if(!p.ok||!c.ok)return NextResponse.json({error:'Unable to load cloud catalog'},{status:502});return NextResponse.json({products:await p.json(),categories:await c.json()})}
async function snapshot(request:Request){const s=readSession(request);if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});if(!config())return NextResponse.json({error:'Cloud database is not configured'},{status:503});const resources=['products?select=*','categories?select=*','customers?select=*','bills?select=*&order=bill_date.desc','bill_items?select=*','stock_logs?select=*','expenses?select=*','inquiries?select=*','staff_users?select=id,username,name,role,permissions,active'];const responses=await Promise.all(resources.map(db));if(responses.some(r=>!r.ok))return NextResponse.json({error:'Unable to load cloud data'},{status:502});const [products,categories,customers,bills,items,stockLogs,expenses,inquiries,users]=await Promise.all(responses.map(r=>r.json()));const customerById=new Map(customers.map((c:any)=>[Number(c.id),c]));const itemMap=new Map<number,any[]>();for(const i of items){const arr=itemMap.get(Number(i.bill_id))||[];arr.push({productId:Number(i.product_id),name:i.name_snapshot,qty:Number(i.qty),price:Number(i.price),expense:Number(i.expense),total:Number(i.total)});itemMap.set(Number(i.bill_id),arr)}const billView=bills.map((b:any)=>{const c=customerById.get(Number(b.customer_id))||{id:0,name:'',mobile:'',place:'',balance:0};return{id:Number(b.id),billNo:b.bill_no,date:b.bill_date,customer:{id:Number(c.id),name:c.name,mobile:c.mobile,place:c.place||'',balance:Number(c.balance||0)},items:itemMap.get(Number(b.id))||[],subtotal:Number(b.subtotal),discount:Number(b.discount),total:Number(b.total),paid:Number(b.paid),balance:Number(b.balance),payment:b.payment,expense:Number(b.expense),profit:Number(b.profit),status:'Completed'}});return NextResponse.json({products:products.map((p:any)=>({...p,id:Number(p.id),price:Number(p.price),expense:Number(p.expense),stock:Number(p.stock)})),categories:categories.map((c:any)=>c.name),categoryImages:Object.fromEntries(categories.map((c:any)=>[c.name,c.image||''])),customers:customers.map((c:any)=>({...c,id:Number(c.id),balance:Number(c.balance)})),bills:billView,stockLogs:stockLogs.map((x:any)=>({id:Number(x.id),productId:Number(x.product_id),productName:x.product_name_snapshot,qty:Number(x.qty),expense:Number(x.expense),date:x.log_date,type:x.type})),expenses:expenses.map((x:any)=>({id:Number(x.id),date:x.expense_date,category:x.category,description:x.description||'',amount:Number(x.amount),addedBy:x.added_by})),inquiries:inquiries.map((x:any)=>({id:Number(x.id),date:x.inquiry_date,customerName:x.customer_name,mobile:x.mobile,place:x.place||'',product:x.product||'',description:x.description||'',status:x.status,addedBy:x.added_by})),users:users.map(safeUser)})}
async function upsert(resource:string,rows:any[]){if(!rows.length)return true;const r=await db(resource,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)});return r.ok}
async function sync(request:Request){const s=readSession(request);if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});if(!config())return NextResponse.json({error:'Cloud database is not configured'},{status:503});const body=await request.json();let ok=await upsert('categories?on_conflict=id',(body.categories||[]).map((name:string,i:number)=>({id:i+1,name,image:body.categoryImages?.[name]||''})));ok=ok&&await upsert('products?on_conflict=id',(body.products||[]).map((p:any)=>({...p,id:Number(p.id)})));ok=ok&&await upsert('customers?on_conflict=id',(body.customers||[]).map((c:any)=>({...c,id:Number(c.id),balance:Number(c.balance||0)})));ok=ok&&await upsert('expenses?on_conflict=id',(body.expenses||[]).map((e:any)=>({id:Number(e.id),expense_date:e.date,category:e.category,description:e.description||'',amount:Number(e.amount),added_by:e.addedBy||s.username})));ok=ok&&await upsert('inquiries?on_conflict=id',(body.inquiries||[]).map((i:any)=>({id:Number(i.id),inquiry_date:i.date,customer_name:i.customerName,mobile:i.mobile,place:i.place||'',product:i.product||'',description:i.description||'',status:i.status,added_by:i.addedBy||s.username})));if(!ok)return NextResponse.json({error:'Cloud sync failed'},{status:502});return NextResponse.json({ok:true})}
async function createBill(request:Request){const s=readSession(request);if(!s||(!s.permissions.includes('sales')&&s.role!=='admin'))return NextResponse.json({error:'Forbidden'},{status:403});if(!config())return NextResponse.json({error:'Cloud database is not configured'},{status:503});const body=await request.json();if(!body?.billNo||!body?.billDate||!body?.customer||!Array.isArray(body.items)||!body.items.length)return NextResponse.json({error:'Invalid bill data'},{status:400});const rpc=await db('rpc/create_bill_transaction',{method:'POST',body:JSON.stringify({id:Number(body.id),bill_no:String(body.billNo),bill_date:String(body.billDate),customer:{id:Number(body.customer.id),name:String(body.customer.name),mobile:String(body.customer.mobile),place:String(body.customer.place||''),balance:Number(body.customer.balance||0)},items:body.items.map((i:any)=>({product_id:Number(i.productId),name:String(i.name),qty:Number(i.qty),price:Number(i.price),expense:Number(i.expense||0),total:Number(i.total)})),subtotal:Number(body.subtotal||0),discount:Number(body.discount||0),total:Number(body.total||0),paid:Number(body.paid||0),payment:body.payment,expense:Number(body.expense||0),profit:Number(body.profit||0)})});if(!rpc.ok){const text=await rpc.text();return NextResponse.json({error:text||'Bill transaction failed'},{status:400})}return NextResponse.json({ok:true,billId:await rpc.json()})}
export async function GET(request:Request){const {searchParams}=new URL(request.url);const resource=searchParams.get('resource');if(resource==='auth-session')return session(request);if(resource==='catalog')return catalog();if(resource==='snapshot')return snapshot(request);return settingsGet()}
export async function POST(request:Request){const {searchParams}=new URL(request.url);const resource=searchParams.get('resource');if(resource==='auth-login')return authLogin(request);if(resource==='auth-logout')return logout();if(resource==='sync')return sync(request);if(resource==='bill')return createBill(request);return NextResponse.json({error:'Unknown resource'},{status:404})}
export async function PUT(request:Request){const {searchParams}=new URL(request.url);if(searchParams.get('resource')==='sync')return sync(request);return settingsPut(request)}
