'use client';
import {createContext,useContext,useEffect,useMemo,useState,ReactNode} from 'react';
import {Bill,Customer,Product,Role,StockLog,seedCustomers,seedProducts,today} from './data';
type Ctx={products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;customers:Customer[];setCustomers:React.Dispatch<React.SetStateAction<Customer[]>>;bills:Bill[];setBills:React.Dispatch<React.SetStateAction<Bill[]>>;stockLogs:StockLog[];setStockLogs:React.Dispatch<React.SetStateAction<StockLog[]>>;role:Role;setRole:React.Dispatch<React.SetStateAction<Role>>;logged:boolean;setLogged:React.Dispatch<React.SetStateAction<boolean>>;hydrated:boolean;toast:(s:string)=>void};
const Store=createContext<Ctx|null>(null);
function usePersist<T>(key:string,initial:T){const[v,setV]=useState(initial);const[ready,setReady]=useState(false);useEffect(()=>{try{const x=localStorage.getItem(key);if(x)setV(JSON.parse(x))}catch{}setReady(true)},[key]);useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(v))},[key,v,ready]);return[v,setV] as const}
export function StoreProvider({children}:{children:ReactNode}){const[products,setProducts]=usePersist('noor_products_v4',seedProducts);const[customers,setCustomers]=usePersist('noor_customers_v4',seedCustomers);const[bills,setBills]=usePersist<Bill[]>('noor_bills_v4',[]);const[stockLogs,setStockLogs]=usePersist<StockLog[]>('noor_stock_logs_v4',[]);const[role,setRole]=useState<Role>('admin');const[logged,setLogged]=useState(false);const[hydrated,setHydrated]=useState(false);useEffect(()=>{const r=localStorage.getItem('noor_role') as Role|null;if(r){setRole(r);setLogged(true)}setHydrated(true)},[]);const toast=(s:string)=>{window.dispatchEvent(new CustomEvent('noor-toast',{detail:s}))};return <Store.Provider value={{products,setProducts,customers,setCustomers,bills,setBills,stockLogs,setStockLogs,role,setRole,logged,setLogged,hydrated,toast}}>{children}</Store.Provider>}
export function useStore(){const c=useContext(Store);if(!c)throw new Error('StoreProvider missing');return c}
export function useToast(){const[s,setS]=useState('');useEffect(()=>{const f=(e:Event)=>{setS((e as CustomEvent).detail);setTimeout(()=>setS(''),2200)};window.addEventListener('noor-toast',f);return()=>window.removeEventListener('noor-toast',f)},[]);return s}
