'use client';
import {createContext,useContext,useEffect,useMemo,useState,ReactNode} from 'react';
import {Bill,Customer,ExpenseEntry,Inquiry,Product,Role,StockLog,seedCustomers,seedProducts,categories as seedCategories} from './data';
export const PERMISSIONS=['dashboard','products','sales','stock','expenses','reports','bills','customers','inquiry','settings','categories'] as const;
export type Permission=typeof PERMISSIONS[number];
export type User={id:number;username:string;password:string;role:Role;name:string;permissions:Permission[]};
const allPermissions:Permission[]=[...PERMISSIONS];
const seedUsers:User[]=[{id:1,username:'admin',password:'admin123',role:'admin',name:'Administrator',permissions:allPermissions},{id:2,username:'staff',password:'staff123',role:'staff',name:'Staff Member',permissions:allPermissions.filter(p=>p!=='categories')}];
type Ctx={products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;customers:Customer[];setCustomers:React.Dispatch<React.SetStateAction<Customer[]>>;bills:Bill[];setBills:React.Dispatch<React.SetStateAction<Bill[]>>;stockLogs:StockLog[];setStockLogs:React.Dispatch<React.SetStateAction<StockLog[]>>;expenses:ExpenseEntry[];setExpenses:React.Dispatch<React.SetStateAction<ExpenseEntry[]>>;inquiries:Inquiry[];setInquiries:React.Dispatch<React.SetStateAction<Inquiry[]>>;users:User[];setUsers:React.Dispatch<React.SetStateAction<User[]>>;categories:string[];setCategories:React.Dispatch<React.SetStateAction<string[]>>;categoryImages:Record<string,string>;setCategoryImages:React.Dispatch<React.SetStateAction<Record<string,string>>>;currentUser:User|null;role:Role;setRole:React.Dispatch<React.SetStateAction<Role>>;logged:boolean;setLogged:React.Dispatch<React.SetStateAction<boolean>>;login:(u:string,p:string)=>User|null;logout:()=>void;hydrated:boolean;toast:(s:string)=>void};
const Store=createContext<Ctx|null>(null);
function usePersist<T>(key:string,initial:T){const[v,setV]=useState(initial);const[ready,setReady]=useState(false);useEffect(()=>{try{const x=localStorage.getItem(key);if(x)setV(JSON.parse(x))}catch{}setReady(true)},[key]);useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(v))},[key,v,ready]);return[v,setV] as const}
export function StoreProvider({children}:{children:ReactNode}){const[products,setProducts]=usePersist('noor_products_v4',seedProducts);const[customers,setCustomers]=usePersist('noor_customers_v4',seedCustomers);const[bills,setBills]=usePersist<Bill[]>('noor_bills_v4',[]);const[stockLogs,setStockLogs]=usePersist<StockLog[]>('noor_stock_logs_v4',[]);const[expenses,setExpenses]=usePersist<ExpenseEntry[]>('travel_expenses_v1',[]);const[inquiries,setInquiries]=usePersist<Inquiry[]>('travel_inquiries_v1',[]);const[users,setUsers]=usePersist<User[]>('noor_users_v1',seedUsers);const[categories,setCategories]=usePersist<string[]>('travel_categories_v1',seedCategories);const[categoryImages,setCategoryImages]=usePersist<Record<string,string>>('travel_category_images_v1',{});const[role,setRole]=useState<Role>('admin');const[logged,setLogged]=useState(false);const[currentUsername,setCurrentUsername]=useState<string|null>(null);const[hydrated,setHydrated]=useState(false);const[cloudReady,setCloudReady]=useState(false);
useEffect(()=>{let active=true;(async()=>{try{const res=await fetch('/api/site-settings?resource=auth-session',{cache:'no-store'});if(res.ok){const data=await res.json();const u=data.user;if(u){setCurrentUsername(u.username);setRole(u.role);setLogged(true)}}}catch{}if(active)setHydrated(true)})();return()=>{active=false}},[]);
useEffect(()=>{if(!users.length)return;setUsers(prev=>prev.map(u=>{const permissions=Array.isArray(u.permissions)?u.permissions:[];if(u.role!=='staff')return {...u,permissions};return {...u,permissions:Array.from(new Set([...permissions,'expenses','inquiry'])) as Permission[]}}))},[]);
useEffect(()=>{setCustomers(prev=>prev.filter(c=>!(c.id===1&&c.name==='Irfan'&&c.mobile==='8589868773')&&!(c.id===2&&c.name==='Sajad Yoosu'&&c.mobile==='5646546546')&&!(c.id===3&&c.name==='Ayesha'&&c.mobile==='9876543210')))},[]);
useEffect(()=>{if(!hydrated)return;let active=true;(async()=>{try{const res=await fetch(logged?'/api/site-settings?resource=snapshot':'/api/site-settings?resource=catalog',{cache:'no-store'});if(!res.ok){if(active&&logged)toast('Cloud database is not connected');return}const data=await res.json();if(logged&&data.products){setProducts(data.products);setCategories(data.categories||[]);setCategoryImages(data.categoryImages||{});setCustomers(data.customers||[]);setBills(data.bills||[]);setStockLogs(data.stockLogs||[]);setExpenses(data.expenses||[]);setInquiries(data.inquiries||[]);setUsers(data.users||[])}else if(data.products){setProducts(data.products);setCategories(data.categories||[]);setCategoryImages(data.categoryImages||{})}if(active)setCloudReady(true)}catch{if(active&&logged)toast('Cloud sync unavailable')}})();return()=>{active=false}},[hydrated,logged]);
useEffect(()=>{if(!cloudReady||!logged)return;const timer=window.setTimeout(async()=>{try{const res=await fetch('/api/site-settings?resource=sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({products,customers,bills,stockLogs,expenses,inquiries,categories,categoryImages}),cache:'no-store'});if(!res.ok)toast('Cloud save failed — changes were not confirmed')}catch{toast('Cloud save failed — check your connection')}},350);return()=>window.clearTimeout(timer)},[products,customers,bills,stockLogs,expenses,inquiries,categories,categoryImages,logged,cloudReady]);
const currentUser=useMemo(()=>users.find(u=>u.username===currentUsername)||null,[users,currentUsername]);function login(u:string,p:string){const found=users.find(x=>x.username.toLowerCase()===u.trim().toLowerCase()&&x.password===p);if(!found)return null;setCurrentUsername(found.username);setRole(found.role);setLogged(true);localStorage.setItem('noor_user',found.username);localStorage.setItem('noor_role',found.role);return found}function logout(){fetch('/api/site-settings?resource=auth-logout',{method:'POST'}).catch(()=>{});setLogged(false);setCurrentUsername(null);localStorage.removeItem('noor_user');localStorage.removeItem('noor_role')}const toast=(s:string)=>{window.dispatchEvent(new CustomEvent('noor-toast',{detail:s}))};return <Store.Provider value={{products,setProducts,customers,setCustomers,bills,setBills,stockLogs,setStockLogs,expenses,setExpenses,inquiries,setInquiries,users,setUsers,categories,setCategories,categoryImages,setCategoryImages,currentUser,role,setRole,logged,setLogged,login,logout,hydrated,toast}}>{children}</Store.Provider>}
export function useStore(){const c=useContext(Store);if(!c)throw new Error('StoreProvider missing');return c}
export function useToast(){const[s,setS]=useState('');useEffect(()=>{const f=(e:Event)=>{setS((e as CustomEvent).detail);setTimeout(()=>setS(''),2200)};window.addEventListener('noor-toast',f);return()=>window.removeEventListener('noor-toast',f)},[]);return s}
