'use client';
import {useRef,useState} from 'react';
import {FolderPlus,Pencil,Trash2,Upload,Image as ImageIcon,X,Save,Layers3} from 'lucide-react';
import {useStore} from '@/lib/store';
import {Panel} from '@/components/Panel';
export default function Categories(){const{categories,setCategories,categoryImages,setCategoryImages,products,setProducts,toast}=useStore();const[name,setName]=useState('');const[edit,setEdit]=useState<string|null>(null);const[fileRef]=useState(()=>({current:null as HTMLInputElement|null}));
 function choose(file?:File){if(!file)return;if(!file.type.startsWith('image/')){toast('Please select an image file');return}if(file.size>3*1024*1024){toast('Category image must be 3MB or smaller');return}const r=new FileReader();r.onload=()=>setCategoryImages(v=>({...v,[edit||'__new__']:String(r.result||'')}));r.readAsDataURL(file)}
 function save(){const n=name.trim();if(!n){toast('Enter category name');return}const duplicate=categories.some(c=>c.toLowerCase()===n.toLowerCase()&&c!==edit);if(duplicate){toast('Category already exists');return}if(edit){setCategories(v=>v.map(c=>c===edit?n:c));setProducts(v=>v.map(p=>p.category===edit?{...p,category:n}:p));setCategoryImages(v=>{const next={...v};if(next[edit]){next[n]=next[edit];delete next[edit]}return next});toast('Category updated')}else{setCategories(v=>[...v,n]);setCategoryImages(v=>{const next={...v};if(next.__new__){next[n]=next.__new__;delete next.__new__}return next});toast('Category added')}setName('');setEdit(null)}
 function startEdit(c:string){setEdit(c);setName(c)}
 function remove(c:string){const count=products.filter(p=>p.category===c).length;if(count){toast(`Cannot delete: ${count} product(s) use this category`);return}if(confirm(`Delete category “${c}”?`)){setCategories(v=>v.filter(x=>x!==c));setCategoryImages(v=>{const next={...v};delete next[c];return next});toast('Category deleted')}}
 const image=edit?categoryImages[edit]:categoryImages.__new__;
 return <div><div className="page-toolbar"><div><h2>Category Management</h2><p>Add, rename, image and remove product categories.</p></div><span className="admin-tag"><Layers3 size={13}/> ADMIN ONLY</span></div><div className="two-col"><Panel><h3>{edit?'Edit Category':'Add New Category'}</h3><label>Category Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. New Gift Collection" onKeyDown={e=>{if(e.key==='Enter')save()}}/></label><div className="upload" onClick={()=>fileRef.current?.click()}><input ref={el=>{fileRef.current=el}} type="file" accept="image/*" hidden onChange={e=>choose(e.target.files?.[0])}/>{image?<><img src={image} alt="Category preview" style={{width:72,height:72,objectFit:'cover',borderRadius:12}}/><b>Change Category Image</b></>:<><ImageIcon size={28}/><b>Upload Category Image</b><span>JPG, PNG, WEBP or GIF · Max 3MB</span></>}</div><div className="modal-actions">{edit&&<button onClick={()=>{setEdit(null);setName('');}}>Cancel</button>}<button className="primary-btn" onClick={save}>{edit?<Save size={16}/>:<FolderPlus size={16}/>} {edit?'Save Category':'Add Category'}</button></div></Panel><Panel><div className="category-admin-grid">{categories.map(c=><div key={c} className="panel" style={{padding:12}}><div style={{display:'flex',gap:10,alignItems:'center'}}>{categoryImages[c]?<img src={categoryImages[c]} alt={c} style={{width:54,height:54,objectFit:'cover',borderRadius:10}}/>:<div style={{width:54,height:54,borderRadius:10,background:'var(--mint)',display:'grid',placeItems:'center'}}><ImageIcon size={20}/></div>}<div style={{flex:1}}><b>{c}</b><small style={{display:'block',color:'var(--muted)',marginTop:4}}>{products.filter(p=>p.category===c).length} product(s)</small></div></div><div className="row-actions" style={{marginTop:10}}><button onClick={()=>startEdit(c)}><Pencil size={15}/></button><button className="danger" onClick={()=>remove(c)}><Trash2 size={15}/></button></div></div>)}</div></Panel></div></div>}
